organization: linuxonzapps
scan_organization: false  # If true, scan all repos in my-org
repositories:           # Optional: Explicitly list repos if scan_organization is false
  - name: spire
    url: https://github.com/linuxonzapps/spire
    commit: main
  - name: terraform
    url: https://github.com/linuxonzapps/terraform
    commit: main
  - name: bazel
    url: https://github.com/linuxonzapps/bazel
    commit: main
  - name: kind
    url: https://github.com/linuxonzapps/kind
    commit: main
  - name: minio
    url: https://github.com/linuxonzapps/minio
    commit: main
  - name: spark
    url: https://github.com/linuxonzapps/spark
    commit: main
  - name: envoy
    url: https://github.com/linuxonzapps/envoy
    commit: main
  - name: opa
    url: https://github.com/linuxonzapps/opa
    commit: main
  - name: netty-tcnative
    url: https://github.com/linuxonzapps/netty-tcnative
    commit: main
  - name: erlang
    url: https://github.com/linuxonzapps/erlang
    commit: main
  - name: sysdig
    url: https://github.com/linuxonzapps/sysdig
    commit: main
  - name: openresty
    url: https://github.com/linuxonzapps/openresty
    commit: main
  - name: postgresql
    url: https://github.com/linuxonzapps/postgresql
    commit: main
#default_schedule: "0 * * * *"  # Hourly builds
default_webhook: true
script_repositories:
  - name: linux-on-ibm-z-scripts
    url: https://github.com/linux-on-ibm-z/scripts
